"""Build the load-on-demand Gate 2 response archive from retained campaign evidence."""

from __future__ import annotations

import csv
import html
import json
import re
import shutil
from collections import defaultdict
from pathlib import Path

DASH_DIR = Path(__file__).resolve().parent
REPO_ROOT = DASH_DIR.parents[1]
CAMPAIGN = REPO_ROOT / "bench/measurements/campaign-20260913-balanced-models"
DEFAULT_OUT = DASH_DIR / "evidence/gate-2"
MARKER = ".muta-gate-two-evidence"

DATASETS = (
    {
        "id": "arc-easy-500",
        "label": "ARC-Easy · n=500 (aggregate only)",
        "description": "One official-profiler accuracy-path aggregate per artifact. Per-item choices and log-likelihoods were not retained.",
        "kind": "aggregate",
    },
    {
        "id": "mac-stem",
        "label": "STEM battery · Mac · 100 prompts",
        "description": "The complete matched 100-prompt raw-completion comparison. Falcon did not produce STEM responses.",
        "kind": "responses",
    },
    {
        "id": "gcp-judges",
        "label": "Gate 1 replay · GCP scalar · 10 prompts",
        "description": "Primary local final-answer rubric. Falcon stopped after five captures and remains unranked.",
        "kind": "responses",
    },
    {
        "id": "mac-judges",
        "label": "Gate 1 replay · Mac · 10 prompts",
        "description": "Paired development-host replay. Falcon stopped after three captures and remains unranked.",
        "kind": "responses",
    },
    {
        "id": "gcp-stem-original",
        "label": "STEM capture · GCP scalar · original attempt",
        "description": "Original GCP scalar attempt: nine complete models and 35 Qwen3.5 Q4_K_M prompts. It is not the matched Mac ranking.",
        "kind": "responses",
    },
    {
        "id": "gcp-stem-restart",
        "label": "STEM capture · GCP scalar · restart fragment",
        "description": "A separate 28-prompt Qwen3.5 Q4_K_M restart. Records overlap the original attempt and are not added to it.",
        "kind": "responses",
    },
    {
        "id": "gcp-stem-vector",
        "label": "STEM capture · GCP vector · remainder attempt",
        "description": "A separate vector capture containing 100 Qwen3.5 Q4_K_M and 100 VibeThinker prompts.",
        "kind": "responses",
    },
)

ATTEMPT_STATES = {
    "gcp-stem-vector": {
        "Falcon-H1R-0.6B-Q4_K_M.gguf": {
            "status": "failed",
            "label": "Failed; no response",
            "reason": "The retained attempt inventory records a runtime failure before any response was captured.",
        },
        "nvidia_OpenReasoning-Nemotron-1.5B-Q4_K_M.gguf": {
            "status": "not_reached",
            "label": "Not reached",
            "reason": "The retained attempt inventory records that this model was not reached.",
        },
    }
}


def _read_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _prepare_out(out: Path) -> None:
    if out.is_file():
        raise SystemExit(f"Gate 2 evidence output is a file: {out}")
    if out.is_dir():
        if not (out / MARKER).is_file():
            raise SystemExit(f"Refusing to clear unmarked Gate 2 evidence directory: {out}")
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text("Generated by build_gate_two_evidence.py; safe to replace.\n")


def _campaign_rows() -> tuple[list[dict], list[dict]]:
    with (CAMPAIGN / "results.csv").open(newline="", encoding="utf-8") as handle:
        results = list(csv.DictReader(handle))
    with (CAMPAIGN / "artifacts.csv").open(newline="", encoding="utf-8") as handle:
        artifacts = list(csv.DictReader(handle))
    return results, artifacts


def _model_catalog(results: list[dict]) -> tuple[list[dict], dict[str, dict]]:
    catalog = []
    by_artifact = {}
    for row in results:
        item = {
            "id": _slug(row["artifact"]),
            "label": row["model"],
            "artifact": row["artifact"],
            "rank": int(row["rank"]),
        }
        catalog.append(item)
        by_artifact[row["artifact"]] = item
    return catalog, by_artifact


def _write_model_dataset(
    out: Path,
    dataset_id: str,
    catalog: list[dict],
    by_artifact: dict[str, dict],
    rows: list[dict],
    grades: dict[tuple[str, str], dict] | None = None,
    expected_count: int | None = None,
    attempt_states: dict[str, dict] | None = None,
) -> list[dict]:
    grades = grades or {}
    attempt_states = attempt_states or {}
    grouped: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        grouped[row.get("model", "")].append(row)

    dataset_dir = out / "datasets" / dataset_id
    dataset_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for model in catalog:
        artifact = model["artifact"]
        records = []
        for source in grouped.get(artifact, []):
            record = dict(source)
            grade = grades.get((artifact, str(source.get("id", ""))))
            if grade:
                record["review"] = grade
            records.append(record)
        records.sort(key=lambda item: str(item.get("id", "")))
        attempt = attempt_states.get(artifact)
        if attempt is None:
            if records and expected_count and len(records) >= expected_count:
                attempt = {"status": "complete", "label": "Complete capture"}
            elif records:
                attempt = {"status": "partial", "label": "Partial capture"}
            else:
                attempt = {
                    "status": "no_capture_recorded",
                    "label": "No capture recorded",
                    "reason": "The retained attempt inventory provides no more specific execution state.",
                }
        payload = {
            "dataset": dataset_id,
            "model": model,
            "records": records,
            "captured": len(records),
            "attempt": attempt,
        }
        relative = f"datasets/{dataset_id}/{model['id']}.json"
        (out / relative).write_text(
            json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"
        )
        entries.append({**model, "captured": len(records), "attempt": attempt, "path": relative})
    return entries


def _stem_grades(directory: Path) -> dict[tuple[str, str], dict]:
    grades = {}
    for path in sorted(directory.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        model = payload.get("model")
        if not model:
            continue
        for result in payload.get("results", []):
            grades[(model, str(result["id"]))] = {
                key: result.get(key)
                for key in ("strict_pass", "core_answer_correct", "reason", "flags")
            }
    return grades


def _judge_grades(directory: Path) -> dict[tuple[str, str], dict]:
    grades = {}
    for path in sorted(directory.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        for model in payload.get("models", []):
            model_key = model.get("model")
            artifact_key = model.get("artifact")
            if model_key and artifact_key and model_key != artifact_key:
                raise ValueError(
                    f"Conflicting model and artifact keys in {path}: "
                    f"{model_key!r} != {artifact_key!r}"
                )
            artifact = model_key or artifact_key
            if not artifact:
                raise ValueError(f"Missing model/artifact key in {path}")
            for prompt in model.get("prompts", []):
                grades[(artifact, str(prompt["id"]))] = {
                    key: prompt.get(key)
                    for key in (
                        "score",
                        "max_score",
                        "final_output_status",
                        "passed_criteria",
                        "criteria",
                        "reason",
                        "flags",
                    )
                }
    return grades


def _write_arc_dataset(
    out: Path, catalog: list[dict], by_artifact: dict[str, dict], results: list[dict]
) -> list[dict]:
    dataset_dir = out / "datasets/arc-easy-500"
    dataset_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for row in results:
        model = by_artifact[row["artifact"]]
        aggregate = {
            "benchmark": "ARC-Easy",
            "metric": "acc_norm",
            "samples": int(row["accuracy_samples"]),
            "accuracy_percent": float(row["accuracy_percent"]),
            "ci95_low_percent": float(row["accuracy_ci95_low_percent"]),
            "ci95_high_percent": float(row["accuracy_ci95_high_percent"]),
            "availability": "aggregate_only",
            "limitation": "The retained accuracy JSONL stores the aggregate task row only. It contains no item IDs, documents, answer options, targets, predictions, or log-likelihood samples.",
        }
        payload = {"dataset": "arc-easy-500", "model": model, "aggregate": aggregate, "records": []}
        relative = f"datasets/arc-easy-500/{model['id']}.json"
        (out / relative).write_text(json.dumps(payload, separators=(",", ":")) + "\n")
        entries.append({**model, "captured": 0, "aggregate": aggregate, "path": relative})
    return entries


def _copy_raw(out: Path) -> list[dict]:
    def redact_paths(value, key=""):
        if isinstance(value, dict):
            return {item_key: redact_paths(item, item_key) for item_key, item in value.items()}
        if isinstance(value, list):
            return [redact_paths(item, key) for item in value]
        if isinstance(value, str) and key not in {
            "answer",
            "reasoning_content",
            "text",
            "expected",
        }:
            return re.sub(
                r"/(?:home|Users|tmp|private/tmp)/[^\s,;\"'`]+",
                "<local-path>",
                value,
            )
        return value

    def copy_published(source: Path, target: Path) -> None:
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix == ".jsonl":
            rows = [redact_paths(row) for row in _read_jsonl(source)]
            target.write_text(
                "".join(
                    json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n"
                    for row in rows
                ),
                encoding="utf-8",
            )
        elif source.suffix == ".json":
            payload = redact_paths(json.loads(source.read_text(encoding="utf-8")))
            target.write_text(
                json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n",
                encoding="utf-8",
            )
        else:
            shutil.copy2(source, target)

    raw_out = out / "raw"
    raw_out.mkdir()
    copied = []
    single_files = (
        "results.csv",
        "judges-ranking.csv",
        "artifacts.csv",
        "report.md",
        "stem-report.md",
        "judges-report.md",
        "README.md",
        "ADJUDICATION.md",
        "gcp-stem-attempts.md",
        "gcp-judges-responses.md",
        "prompt-responses.md",
        "host-completion.md",
    )
    for name in single_files:
        source = CAMPAIGN / name
        if source.is_file():
            copy_published(source, raw_out / name)
            copied.append({"label": name, "path": f"raw/{name}"})
    failure = CAMPAIGN / "failures/falcon-gcp-scalar.md"
    copy_published(failure, raw_out / "failures/falcon-gcp-scalar.md")
    copied.append(
        {
            "label": "Falcon GCP scalar failure",
            "path": "raw/failures/falcon-gcp-scalar.md",
        }
    )
    gcp_files = (
        "accuracy.jsonl",
        "throughput.jsonl",
        "vector-throughput.jsonl",
        "judges-events.jsonl",
        "judges-responses.jsonl",
        "stem-events.jsonl",
        "stem-events-gcp-remainder.jsonl",
        "stem-events-vector-remainder.jsonl",
        "stem-responses.jsonl",
        "stem-responses-gcp-remainder.jsonl",
        "stem-responses-vector-remainder.jsonl",
    )
    for name in gcp_files:
        source = CAMPAIGN / "raw" / name
        target = raw_out / "raw" / source.name
        copy_published(source, target)
        copied.append(
            {
                "label": f"GCP published record · {source.name}",
                "path": f"raw/raw/{source.name}",
            }
        )
    for source in sorted((CAMPAIGN / "mac-accuracy").glob("*/*/*")):
        if not source.is_file() or source.name not in {
            "complete.json",
            "config.json",
            "events.jsonl",
            "responses.jsonl",
        }:
            continue
        relative = source.relative_to(CAMPAIGN / "mac-accuracy")
        target = raw_out / "mac-accuracy" / relative
        copy_published(source, target)
        copied.append(
            {
                "label": f"Mac published record · {relative.as_posix()}",
                "path": f"raw/mac-accuracy/{relative.as_posix()}",
            }
        )
    for directory in (
        "manual-stem",
        "manual-stem-mac",
        "manual-judges",
        "manual-judges-gcp",
    ):
        source_dir = CAMPAIGN / directory
        for source in sorted(source_dir.rglob("*")):
            if not source.is_file():
                continue
            relative = source.relative_to(source_dir)
            target = raw_out / directory / relative
            copy_published(source, target)
            copied.append(
                {
                    "label": f"Assessment · {directory}/{relative.as_posix()}",
                    "path": f"raw/{directory}/{relative.as_posix()}",
                }
            )
    for source in sorted((CAMPAIGN / "transcripts").glob("*/*/*.md")):
        relative = source.relative_to(CAMPAIGN / "transcripts")
        target = raw_out / "transcripts" / relative
        copy_published(source, target)
        copied.append(
            {
                "label": f"Transcript · {relative.as_posix()}",
                "path": f"raw/transcripts/{relative.as_posix()}",
            }
        )
    for directory in sorted(path for path in raw_out.rglob("*") if path.is_dir()):
        links = []
        for child in sorted(
            directory.iterdir(), key=lambda item: (item.is_file(), item.name.lower())
        ):
            label = f"{child.name}/" if child.is_dir() else child.name
            href = f"{child.name}/" if child.is_dir() else child.name
            links.append(f'<li><a href="{html.escape(href)}">{html.escape(label)}</a></li>')
        (directory / "index.html").write_text(
            '<!doctype html><html lang="en"><meta charset="utf-8">'
            f"<title>{html.escape(directory.name)} evidence files</title>"
            f"<h1>{html.escape(directory.name)} evidence files</h1><ul>{''.join(links)}</ul>",
            encoding="utf-8",
        )

    markdown_link = re.compile(r"\[([^\]]+)\]\((<?)([^)\n>]+)(>?)\)")
    for document in raw_out.rglob("*.md"):

        def keep_available(match: re.Match, document: Path = document) -> str:
            target = match.group(3)
            if target.startswith(("http://", "https://", "mailto:", "#")):
                return match.group(0)
            destination = (document.parent / target.split("#", 1)[0]).resolve()
            if destination.is_file() or (
                destination.is_dir() and (destination / "index.html").is_file()
            ):
                return match.group(0)
            return (
                f"{match.group(1)} (source path: `{target}`; not included in the published bundle)"
            )

        text = document.read_text(encoding="utf-8")
        document.write_text(markdown_link.sub(keep_available, text), encoding="utf-8")
    return copied


def build(out: Path = DEFAULT_OUT) -> Path:
    if not CAMPAIGN.is_dir():
        raise SystemExit(f"Gate 2 campaign is missing: {CAMPAIGN}")
    results, artifacts = _campaign_rows()
    catalog, by_artifact = _model_catalog(results)
    _prepare_out(out)

    datasets = {item["id"]: dict(item) for item in DATASETS}
    datasets["arc-easy-500"]["models"] = _write_arc_dataset(out, catalog, by_artifact, results)

    mac_stem = []
    mac_judges = []
    for model in catalog:
        model_dir = CAMPAIGN / "mac-accuracy" / model["artifact"]
        mac_stem.extend(_read_jsonl(model_dir / "stem/responses.jsonl"))
        mac_judges.extend(_read_jsonl(model_dir / "judges/responses.jsonl"))
    datasets["mac-stem"]["models"] = _write_model_dataset(
        out,
        "mac-stem",
        catalog,
        by_artifact,
        mac_stem,
        _stem_grades(CAMPAIGN / "manual-stem-mac"),
        expected_count=100,
    )
    datasets["gcp-judges"]["models"] = _write_model_dataset(
        out,
        "gcp-judges",
        catalog,
        by_artifact,
        _read_jsonl(CAMPAIGN / "raw/judges-responses.jsonl"),
        _judge_grades(CAMPAIGN / "manual-judges-gcp"),
        expected_count=10,
    )
    datasets["mac-judges"]["models"] = _write_model_dataset(
        out,
        "mac-judges",
        catalog,
        by_artifact,
        mac_judges,
        _judge_grades(CAMPAIGN / "manual-judges"),
        expected_count=10,
    )
    datasets["gcp-stem-original"]["models"] = _write_model_dataset(
        out,
        "gcp-stem-original",
        catalog,
        by_artifact,
        _read_jsonl(CAMPAIGN / "raw/stem-responses.jsonl"),
        _stem_grades(CAMPAIGN / "manual-stem"),
        expected_count=100,
    )
    datasets["gcp-stem-restart"]["models"] = _write_model_dataset(
        out,
        "gcp-stem-restart",
        catalog,
        by_artifact,
        _read_jsonl(CAMPAIGN / "raw/stem-responses-gcp-remainder.jsonl"),
        expected_count=100,
    )
    datasets["gcp-stem-vector"]["models"] = _write_model_dataset(
        out,
        "gcp-stem-vector",
        catalog,
        by_artifact,
        _read_jsonl(CAMPAIGN / "raw/stem-responses-vector-remainder.jsonl"),
        expected_count=100,
        attempt_states=ATTEMPT_STATES["gcp-stem-vector"],
    )

    manifest = {
        "schema_version": 1,
        "campaign": "campaign-20260913-balanced-models",
        "models": catalog,
        "datasets": [datasets[item["id"]] for item in DATASETS],
        "excluded_artifacts": [
            {
                "model": row["model"],
                "artifact": row["test_artifact"],
                "reason": row["runtime_gate"],
            }
            for row in artifacts
            if row["runtime_gate"] != "pass"
        ],
        "downloads": _copy_raw(out),
    }
    (out / "index.json").write_text(
        json.dumps(manifest, ensure_ascii=False, separators=(",", ":")) + "\n"
    )
    return out


if __name__ == "__main__":
    result = build()
    print(result)
