/* Canonical English added by the release UI, Host, power, resource, privacy, and viewer lanes.
 * This file loads before i18n.js so every advertised locale is validated against the exact
 * integrated surface. Locale-specific release overlays are generated in locale-generated.js. */
"use strict";

(() => {
  globalThis.MutaReleaseEnglish = Object.freeze({
    "settings.appearance": "Appearance",
    "settings.themeSystem": "System",
    "settings.themeLight": "Light",
    "settings.themeDark": "Dark",
    "settings.powerSection": "Power",
    "settings.power": "Muta power optimization",
    "settings.powerHelp": "On battery, Muta shortens its reasoning and replies. Explicit Extended reasoning keeps its full result.",
    "settings.analyticsHelp": "Help us improve Muta by sharing your analytics.",

    "resources.empty": "No learning resources yet.",
    "resources.processing": "Preparing…",
    "resources.ready": "Ready",
    "resources.failed": "Failed",
    "resources.pages": "{count} PDF pages",
    "resources.retry": "Retry",
    "resources.delete": "Delete",
    "resources.uploading": "Uploading {name}…",
    "resources.uploaded": "{name} is being prepared. You can keep chatting.",
    "resources.uploadFailed": "Couldn’t upload that PDF.",
    "resources.loadFailed": "Couldn’t load files.",
    "resources.deleteFailed": "Couldn’t delete that file.",
    "resources.heading": "Files",
    "resources.manageHelp": "Review and manage textbooks and notes used for private, page-cited chat.",
    "resources.learningResources": "Learning resources",
    "resources.attachPdf": "Attach a PDF",
    "rag.noFiles": "No files found",
    "rag.loadingFiles": "Loading files…",
    "rag.loadFailed": "Couldn’t load files — retrying…",
    "rag.remove": "Remove {name}",
    "rag.document": "Document: {name}",
    "rag.openDocument": "Open document {name}",
    "rag.maxFiles": "You can use up to {count} documents in one message.",
    "rag.pickerResults": "{count} ready documents available. Use Up and Down arrows, then Enter.",
    "rag.pickerEmpty": "No ready documents match.",
    "rag.pickerClosed": "Document picker closed.",
    "rag.sourcePage": "{title}, PDF page {page}",
    "rag.openPage": "Open {title} at PDF page {page}",
    "rag.sources": "Sources",
    "rag.sourceCount": "{count} sources",
    "rag.sourceCountOne": "1 source",
    "rag.sourceMeta": "PDF · page {page}",
    "rag.citation": "Citation {number}: {title}, PDF page {page}",
    "rag.previewLabel": "Citation {number}",
    "rag.showSources": "Show {count} sources",
    "rag.hideSources": "Hide {count} sources",

    "power.checking": "Checking host power…",
    "power.checkingHelp": "Reading the battery of the laptop serving Muta.",
    "power.unavailable": "Power information unavailable",
    "power.unavailableHelp": "This device does not expose a battery sensor. Muta still keeps its fixed memory and thermal safeguards.",
    "power.sensorGrace": "Battery sensor temporarily unavailable; Critical reserve remains active.",
    "power.off": "Power optimization off",
    "power.normal": "Balanced",
    "power.eco": "Eco mode",
    "power.critical": "Critical battery mode",
    "power.plugged": "Plugged in",
    "power.connectedDraining": "Power connected; battery still draining",
    "power.battery": "Host battery {percentage}%",
    "power.remaining": "about {time} remaining",
    "power.rate": "{watts} W",
    "power.actions": "Active: {actions}",
    "power.action_limit_auto_reasoning": "bounded automatic reasoning",
    "power.action_limit_response_length": "shorter replies",
    "power.action_direct_responses": "direct responses",
    "power.action_pause_vision": "new image reading paused",
    "power.action_pause_tts": "speech playback paused",
    "power.openSettings": "Open power settings",
    "runtime.eco": "Eco",

    "sidebar.hostLocal": "Muta Host: This device. Running locally.",
    "account.host": "Host",
    "account.member": "Member",
    "account.logout": "Log out",
    "host.title": "Host mode",
    "host.description": "Share this Muta privately with people on the same network.",
    "host.enable": "Enable Host mode",
    "host.memoryLimit": "Memory limit",
    "host.competition": "ADTC competition",
    "host.competitionHelp": "Stay inside the 7 GB competition budget. Extra chats wait in line.",
    "host.system": "Use this system",
    "host.systemHelp": "Detect usable RAM and CPU, then run as many safe chats as this laptop supports.",
    "host.shareAddress": "Share this address",
    "host.joinUrl": "Muta join URL",
    "host.copy": "Copy",
    "host.certificateHelp": "Learners must be on this network. On first use, install Muta’s local certificate, then compare its fingerprint with the host.",
    "host.downloadCertificate": "Download trust certificate",
    "host.people": "People",
    "host.qrAlt": "QR code for the secure Muta join URL",
    "host.waiting": "Waiting for approval",
    "host.removing": "Removing data…",
    "host.approvedSignedIn": "Approved · has signed in",
    "host.approved": "Approved",
    "host.accept": "Accept",
    "host.decline": "Decline",
    "host.remove": "Remove",
    "host.removeConfirm": "Remove {name}? Their account, conversations, files and learning profile will be deleted.",
    "host.removePending": "Revoking access and removing {name}…",
    "host.approveFailed": "Could not approve that account.",
    "host.rejectFailed": "Could not decline that account.",
    "host.removeFailed": "Could not remove that account.",
    "host.readFailed": "Could not read Host mode settings.",
    "host.apply": "Applying the safe chat capacity…",
    "host.updateFailed": "Could not update Host mode.",
    "host.on": "Host mode is on. New replies are queued when all slots are busy.",
    "host.off": "Host mode is off.",
    "host.noFingerprint": "Certificate fingerprint unavailable",
    "host.simultaneousChats": "simultaneous chats",
    "host.tokensPerChat": "tokens per chat",
    "host.ramCeiling": "RAM ceiling",
    "host.accountCount": "{count} account",
    "host.accountCountMany": "{count} accounts",
    "host.empty": "No one has asked to join yet.",
    "host.copied": "Join address copied.",
    "host.copyFallback": "Address selected — copy it from the field.",

    "reply.partialSaved": "Reply interrupted — the partial answer is saved.",
    "reply.continue": "Continue reply",
    "reply.continuePrompt": "Continue the previous incomplete reply from exactly where it stopped. Do not repeat completed parts.",
    "reply.stopping": "Stopping…",
    "reply.preparing": "Preparing response…",
    "reply.writing": "Writing response…",
    "reply.diagram": "Generating diagram…",
    "reply.working": "Working…",

    "access.connecting": "Connecting to this Muta…",
    "access.sharedNearby": "Shared from a nearby laptop",
    "access.welcome": "Welcome to Muta",
    "access.signInPrivate": "Sign in to open your private tutor.",
    "access.openSecure": "Open secure Muta",
    "access.login": "Log in",
    "access.signup": "Sign up",
    "access.username": "Username",
    "access.password": "Password",
    "access.chooseUsername": "Choose a username",
    "access.usernameRules": "3–32 letters or numbers; dots, dashes and underscores are allowed inside.",
    "access.choosePassword": "Choose a password",
    "access.requestJoin": "Ask to join",
    "access.requestSent": "Request sent",
    "access.awaitApproval": "Ask the person hosting Muta to approve you. This page will open automatically.",
    "access.otherAccount": "Use another account",
    "access.dialog": "Account access",
    "access.notSharing": "This laptop is not sharing Muta right now.",
    "access.unreachable": "Could not reach this Muta. Check the network and try again.",

    "privacy.heading": "Privacy",
    "privacy.eyebrow": "Your privacy, your choice",
    "privacy.title": "Help us see where Muta is useful.",
    "privacy.description": "When this laptop gets online, Muta can share pseudonymous product activity and an approximate city-level location derived from its network. This helps us count active installations and map Muta’s reach.",
    "privacy.sends": "Sends a durable random installation ID, app version/build, operating-system and processor family, recent-use time, and active/registered local-user counts.",
    "privacy.neverSends": "Never sends conversations, questions, files, voice, usernames, email, GPS, or the laptop name.",
    "privacy.saved": "Your choice is saved on this laptop, so Muta will not keep asking.",
    "privacy.change": "You can change this in Settings. Turning it off also asks the server to delete this installation’s history.",
    "privacy.keepPrivate": "Keep private",
    "privacy.shareActivity": "Share product activity",
    "privacy.deletionQueued": "Deletion is queued and will complete when this laptop is online.",
    "privacy.synced": "Sharing is on · last synced {date}",
    "privacy.waitingOnline": "Sharing is on · waiting for the next internet connection.",
    "privacy.offline": "Sharing is off. Muta stays fully offline-capable.",
    "privacy.noChoice": "No choice has been saved yet.",
    "privacy.saveChoiceFailed": "Muta could not save that choice. Please try again.",
    "privacy.saveSettingFailed": "Muta could not save that privacy setting. Please try again.",

    "conversation.deleteDefaultBody": "This will delete this chat.",
    "code.text": "Text",
    "theme.switchLight": "Switch to light mode",
    "theme.switchDark": "Switch to dark mode",
    "visualization.title": "Muta visualization",
    "visualization.replay": "Replay",
    "visualization.play": "Play",
    "visualization.pause": "Pause",
    "visualization.restart": "Restart",
    "visualization.controls": "Surface animation controls",
    "visualization.failed": "This visualization could not be drawn.",
    "visualization.incomplete": "The visualization data was incomplete.",
    "visualization.invalid": "The visualization data was not valid.",
    "visualization.rotateHint": "Use arrow keys to rotate.",
    "visualization.orbitalRelationships": "Orbital relationships",
    "visualization.dragRotate": "drag to rotate",
    "visualization.axisDomains": "x: {x0} to {x1} · y: {y0} to {y1} · z vertical"
  });

  if (typeof module !== "undefined" && module.exports) module.exports = globalThis.MutaReleaseEnglish;
})();
