#!/usr/bin/env python3
"""Pack multiple GGUF models into one valid GGUF bundle under name prefixes.

Bundle format (see docs/DUO_POC_PLAN.md):
- top-level general.architecture = "bundle" (unpatched llama.cpp fails fast)
- manifest: bundle.count, bundle.{i}.{prefix,role,arch,source,sha256}
- per source model i: every KV k -> {prefix}k, every tensor t -> {prefix}t,
  tensor payloads copied as raw bytes in their original quant type.

Copy loop mirrors llama.cpp/gguf-py/gguf/scripts/gguf_new_metadata.py (the
version-matched reader->writer pass-through pattern).

Usage:
  pack_bundle.py --out bundle/muta-duo.gguf \
      --model models/SmolLM2-135M-Instruct-Q4_K_M.gguf:m0.:front \
      --model models/Qwen3.5-4B-Q4_K_M.gguf:m1.:expert
  pack_bundle.py --identity models/SmolLM2-135M-Instruct-Q4_K_M.gguf --out /tmp/x.gguf
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import time
from pathlib import Path

import gguf


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 24), b""):
            h.update(chunk)
    return h.hexdigest()


def get_field_str(reader: gguf.GGUFReader, key: str) -> str | None:
    field = reader.get_field(key)
    return field.contents() if field else None


def copy_metadata(reader: gguf.GGUFReader, writer: gguf.GGUFWriter, prefix: str, skip_arch: bool) -> int:
    n = 0
    for field in reader.fields.values():
        # structural pseudo-fields (version/counts) are regenerated by the writer
        if field.name.startswith("GGUF."):
            continue
        # identity mode: the writer already emits general.architecture itself
        if skip_arch and field.name == gguf.Keys.General.ARCHITECTURE:
            continue
        val_type = field.types[0]
        sub_type = field.types[-1] if val_type == gguf.GGUFValueType.ARRAY else None
        writer.add_key_value(prefix + field.name, field.contents(), val_type, sub_type=sub_type)
        n += 1
    return n


def add_tensor_infos(reader: gguf.GGUFReader, writer: gguf.GGUFWriter, prefix: str) -> int:
    n = 0
    for tensor in reader.tensors:
        writer.add_tensor_info(prefix + tensor.name, tensor.data.shape, tensor.data.dtype,
                               tensor.data.nbytes, tensor.tensor_type)
        n += 1
    return n


def write_tensor_payloads(readers: list[gguf.GGUFReader], writer: gguf.GGUFWriter) -> None:
    total = sum(t.n_bytes for r in readers for t in r.tensors)
    done = 0
    t0 = time.time()
    for reader in readers:
        for tensor in reader.tensors:
            writer.write_tensor_data(tensor.data, tensor_endianess=reader.endianess)
            done += tensor.n_bytes
        print(f"  ... {done / 1e9:.2f} / {total / 1e9:.2f} GB written ({time.time() - t0:.0f}s)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, required=True, help="output GGUF path")
    ap.add_argument("--model", action="append", default=[], metavar="PATH:PREFIX:ROLE",
                    help="source model spec, repeatable (prefix like 'm0.', role like 'front')")
    ap.add_argument("--identity", type=Path, default=None, metavar="PATH",
                    help="identity mode: repack one model with empty prefix and its own arch (gate G1)")
    args = ap.parse_args()

    if args.identity is not None:
        if args.model:
            ap.error("--identity and --model are mutually exclusive")
        specs = [(args.identity, "", "identity")]
    else:
        if len(args.model) < 2:
            ap.error("need at least two --model specs (or use --identity)")
        specs = []
        for m in args.model:
            try:
                path, prefix, role = m.rsplit(":", 2)
            except ValueError:
                ap.error(f"bad --model spec (want PATH:PREFIX:ROLE): {m}")
            specs.append((Path(path), prefix, role))

    identity = args.identity is not None

    readers = []
    for path, prefix, role in specs:
        print(f"* Loading {path} (prefix={prefix!r}, role={role})")
        readers.append(gguf.GGUFReader(path, "r"))

    endianess = readers[0].endianess
    if identity:
        arch = get_field_str(readers[0], gguf.Keys.General.ARCHITECTURE)
    else:
        arch = "bundle"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    writer = gguf.GGUFWriter(args.out, arch=arch, endianess=endianess)

    alignment = get_field_str(readers[0], gguf.Keys.General.ALIGNMENT)
    if identity and alignment is not None:
        writer.data_alignment = alignment

    if not identity:
        writer.add_key_value("bundle.count", len(specs), gguf.GGUFValueType.UINT32)
        for i, (path, prefix, role) in enumerate(specs):
            print(f"* Hashing {path}")
            writer.add_key_value(f"bundle.{i}.prefix", prefix, gguf.GGUFValueType.STRING)
            writer.add_key_value(f"bundle.{i}.role", role, gguf.GGUFValueType.STRING)
            writer.add_key_value(f"bundle.{i}.arch", get_field_str(readers[i], gguf.Keys.General.ARCHITECTURE),
                                 gguf.GGUFValueType.STRING)
            writer.add_key_value(f"bundle.{i}.source", path.name, gguf.GGUFValueType.STRING)
            writer.add_key_value(f"bundle.{i}.sha256", sha256_file(path), gguf.GGUFValueType.STRING)

    for reader, (path, prefix, role) in zip(readers, specs):
        n_kv = copy_metadata(reader, writer, prefix, skip_arch=identity)
        n_ti = add_tensor_infos(reader, writer, prefix)
        print(f"* {path.name}: copied {n_kv} KVs, {n_ti} tensor infos")

    print(f"* Writing {args.out}")
    writer.write_header_to_file()
    writer.write_kv_data_to_file()
    writer.write_ti_data_to_file()
    write_tensor_payloads(readers, writer)
    writer.close()
    print(f"* Done: {args.out} ({args.out.stat().st_size / 1e9:.2f} GB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
